### ISSUE TITLE
Can't capture - CallstackDataView crashes on capture start

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4776]
With the latest code, I get 

```
[2023-01-26T15:16:11.409074] [ProducerSideService/ProducerSideServiceImpl.cpp:28] About to send StartCaptureCommand to CaptureEventProducers (if any)
[2023-01-26T15:16:11.409122] [         LinuxTracing/TracerImpl.cpp:753] Error: Could not read cpuset
[2023-01-26T15:16:11.409139] [LinuxCaptureService/LinuxCaptureServiceBase.cpp:283] Starting memory watchdog with threshold 8372432896 B because total physical memory is 16744865792 B
[2023-01-26T15:16:11.409192] [ProducerSideService/ProducerSideServiceImpl.cpp:161] Sent StartCaptureCommand to CaptureEventProducer

[2023-01-26T15:16:11.433805] [       ClientData/CaptureDataHolder.h:33] Check failed: HasCaptureData()
Aborted (core dumped)
```

Instrumenting a single function of a test program with both intrumentation methods.

**Comment by pierricgimmig** [comment]
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737280248256) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737280248256) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737280248256, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff64f6476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff64dc7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055555590ae19 in orbit_client_data::CaptureDataHolder::GetCaptureData() const (this=<optimized out>) at /home/pierric/git/orbit/src/ClientData/include/ClientData/CaptureDataHolder.h:33
#6  0x0000555555b58783 in orbit_data_views::CallstackDataView::GetFrameFromIndex(unsigned long) const (this=this@entry=0x7fff41d02450, index_in_callstack=6)
    at /home/pierric/git/orbit/src/DataViews/CallstackDataView.cpp:247
#7  0x0000555555b59380 in orbit_data_views::CallstackDataView::GetFrameFromRow(int) const (this=0x7fff41d02450, row=<optimized out>) at /home/pierric/git/orbit/src/DataViews/CallstackDataView.cpp:238
#8  orbit_data_views::CallstackDataView::GetDisplayColor(int, int, unsigned char&, unsigned char&, unsigned char&)
    (this=0x7fff41d02450, row=<optimized out>, red=@0x7fffffffc408: 52 '4', green=@0x7fffffffc407: 0 '\000', blue=@0x7fffffffc406: 0 '\000')
    at /home/pierric/git/orbit/src/DataViews/CallstackDataView.cpp:227
#9  0x00005555558e6757 in OrbitTableModel::data(QModelIndex const&, int) const (this=0x55555ce61a30, index=..., role=<optimized out>) at /home/pierric/git/orbit/src/OrbitQt/orbittablemodel.cpp:64
#10 0x00007ffff7a5bed4 in QStyledItemDelegate::initStyleOption(QStyleOptionViewItem*, QModelIndex const&) const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7a5b5f0 in QStyledItemDelegate::sizeHint(QStyleOptionViewItem const&, QModelIndex const&) const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff7aa09f3 in QTreeView::indexRowSizeHint(QModelIndex const&) const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff7aa4391 in QTreeViewPrivate::itemHeight(int) const () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7aa598b in QTreeViewPrivate::updateScrollBars() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff7aafaf5 in QTreeView::updateGeometries() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x0000555555927c1b in OrbitTreeView::resizeEvent(QResizeEvent*) (this=0x55555a4a04c0, event=0x7fffffffc938) at /home/pierric/git/orbit/src/OrbitQt/orbittreeview.cpp:195
#17 0x00005555559275d3 in OrbitTreeView::Initialize(orbit_data_views::DataView*, SelectionType, FontType, bool, QFlags<Qt::AlignmentFlag>)
    (this=0x55555a4a04c0, data_view=<optimized out>, selection_type=SelectionType::kExtended, font_type=FontType::kDefault, uniform_row_height=false, text_alignment=...)
    at /home/pierric/git/orbit/src/OrbitQt/orbittreeview.cpp:97
#18 0x000055555591fdf1 in OrbitDataViewPanel::Initialize(orbit_data_views::DataView*, SelectionType, FontType, bool, QFlags<Qt::AlignmentFlag>)
    (this=0x55555a618740, data_view=0x22710, selection_type=(unknown: 0x6), font_type=(unknown: 0xf654aa7c), uniform_row_height=240, text_alignment=...)
    at /home/pierric/git/orbit/src/OrbitQt/orbitdataviewpanel.cpp:31
#19 0x00005555558e3bd1 in OrbitSamplingReport::Initialize(OrbitApp*, orbit_data_views::DataView*, orbit_client_data::CallstackData const*, orbit_client_data::PostProcessedSamplingData const*)
    (this=0x7fffb8aa9bb0, app=0x5555575de910, callstack_data_view=0x22710, callstack_data=0x0, post_processed_sampling_data=0x0) at /home/pierric/git/orbit/src/OrbitQt/orbitsamplingreport.cpp:64
#20 0x00005555558c78b5 in OrbitMainWindow::SetSamplingReport(orbit_client_data::CallstackData const*, orbit_client_data::PostProcessedSamplingData const*)
    (this=0x7fffffffd5b0, callstack_data=0x0, post_processed_sampling_data=0x0) at /home/pierric/git/orbit/src/OrbitQt/orbitmainwindow.cpp:812
#21 0x00005555558c792e in non-virtual thunk to OrbitMainWindow::SetSamplingReport(orbit_client_data::CallstackData const*, orbit_client_data::PostProcessedSamplingData const*) ()
    at /home/pierric/git/orbit/src/OrbitQt/orbitmainwindow.cpp:817
#22 0x0000555555983561 in OrbitApp::ClearSamplingReport() (this=0x5555575de910) at /home/pierric/git/orbit/src/OrbitGl/OrbitApp.cpp:1003
--Type <RET> for more, q to quit, c to continue without paging--
#23 OrbitApp::UpdateAfterCaptureCleared() (this=0x5555575de910) at /home/pierric/git/orbit/src/OrbitGl/OrbitApp.cpp:2336
#24 OrbitApp::ClearCapture() (this=this@entry=0x5555575de910) at /home/pierric/git/orbit/src/OrbitGl/OrbitApp.cpp:1430
#25 0x00005555559a27cb in OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3::operator()() (this=0x7fffac099598) at /home/pierric/git/orbit/src/OrbitGl/OrbitApp.cpp:366
#26 orbit_base::CallTaskAndSetResultInPromise<void>::Call<OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3&>(OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3&) (invocable=..., this=<optimized out>) at /home/pierric/git/orbit/src/OrbitBase/include/OrbitBase/PromiseHelpers.h:38
#27 orbit_base::Executor::Schedule<OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3>(OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3&&)::{lambda()#1}::operator()() (this=0x7fffac099598) at /home/pierric/git/orbit/src/OrbitBase/include/OrbitBase/Executor.h:97
#28 NullaryFunctorAction<orbit_base::Executor::Schedule<OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3>(OrbitApp::OnCaptureStarted(orbit_grpc_protos::CaptureStarted const&, std::optional<std::filesystem::__cxx11::path>, absl::lts_20220623::flat_hash_set<unsigned long, absl::lts_20220623::hash_internal::Hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >)::$_3&&)::{lambda()#1}>::Execute() (this=0x7fffac099590) at /home/pierric/git/orbit/src/OrbitBase/include/OrbitBase/Action.h:32
#29 0x0000555556200ed2 in orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0::operator()() const (this=0x7fffac002d00)
    at /home/pierric/git/orbit/src/QtUtils/MainThreadExecutor.cpp:22
#30 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0>::call(orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0&, void**) (f=..., arg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#31 QtPrivate::Functor<orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0, 0>::call<QtPrivate::List<>, void>(orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0&, void*, void**) (f=..., arg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#32 QtPrivate::QFunctorSlotObject<orbit_qt_utils::MainThreadExecutor::ScheduleImpl(std::unique_ptr<Action, std::default_delete<Action> >)::$_0, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=0x7fffac002cf0, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#33 0x00007ffff6cf441e in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff77b8713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff6cc6e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff6cc9f27 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff6d20a67 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5

#38 0x00007ffff5926d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff597b6c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff59243e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff6d200b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff6cc575b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007ffff6ccdcf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00005555558af7a7 in RunUiInstance(std::variant<orbit_session_setup::SignedDebianPackageDeployment, orbit_session_setup::BareExecutableAndRootPasswordDeployment, orbit_session_setup::NoDeployment> const&, orbit_ssh::Context const*, QStringList const&, std::filesystem::__cxx11::path const&, std::optional<orbit_session_setup::ConnectionTarget>)
     (deployment_configuration=std::variant<orbit_session_setup::SignedDebianPackageDeployment, orbit_session_setup::BareExecutableAndRootPasswordDeployment, orbit_session_setup::NoDeployment> [index 0] = {...}, ssh_context=ssh_context@entry=0x7fffffffd838, command_line_flags=..., capture_file_path=filesystem::path "", maybe_connection_target=std::optional<orbit_session_setup::ConnectionTarget> [no contained value])
    at /home/pierric/git/orbit/src/Orbit/main.cpp:138
#45 0x00005555558b52c6 in main(int, char**) (argc=1, argv=0x7fffffffdfc8) at /home/pierric/git/orbit/src/Orbit/main.cpp:376

```

**Comment by pierricgimmig** [comment]
Clear capture resets the CaptureDataHolder, setting its CaptureData to nullptr. A callstack data view is then refreshed and tries to access the CaptureData that was just set to nullptr. Seems related to #4767, @vwbaker , could that be the case?

**Comment by vwbaker** [comment]
Could be, I'll take a look

**Comment by vwbaker** [comment]
From I bisect, we narrowed it down to https://github.com/google/orbit/pull/4712. I have https://github.com/google/orbit/pull/4781 out for a fix

**Comment by vwbaker** [comment]
Closing with https://github.com/google/orbit/pull/4781
